#!/bin/bash
export JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home'
./gradlew plait-core:publish
./gradlew :PlaitPlugin:plait-plugin:publishReleasePublicationToMavenRepository
